// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebdVg9jyt_Z9imrgP1OpFK0RBefYEqGA',
    appId: '1:619455330036:android:05e8f1e18e7c40a86050a1',
    messagingSenderId: '619455330036',
    projectId: 'shopml-ap',
    storageBucket: 'shopml-ap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaos6GPE5HxF28-ANPHf8uo-3KWfuljuk',
    appId: '1:619455330036:ios:627055f76cb0ca436050a1',
    messagingSenderId: '619455330036',
    projectId: 'shopml-ap',
    storageBucket: 'shopml-ap.appspot.com',
    androidClientId: '619455330036-373miuu9c6glv6rusdrvn6c9nl7r2e9d.apps.googleusercontent.com',
    iosClientId: '619455330036-ffh7h0tjskigq7aqlkcfn7hr917jriuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.markethelper',
  );
}
